[server]
host = "0.0.0.0"
port = 8000
production = true

[server.security]
jwt-secret = "testing"

[app]
auth-required = false

[app.events.kafka]
brokers = ["kafka1:9092", "kafka2:9092"]
topic = "microservice-events"
group_id = "rodan-sse-group"

# or, alternatively:
# [app.events.http] # This endpoint only takes post request
# endpoint = "/events/injest"
# api-key = "some-value which will be converted to sha256 and eval"
