[server]
host = "0.0.0.0"
port = 8000
production = true

[server.security]
jwt-secret = "testing1234555"

[app]
auth-required = false
event-logging = true
event-log-file = "events.log"
event-flush-duration = "10m"
event-log-rotation = "8h"

# [app.events.kafka]
# brokers = ["kafka1:9092", "kafka2:9092"]
# topic = "microservice-events"
# group_id = "rodan-sse-group"

# or, alternatively:
[app.events.http]
# Endpoint for HTTP events ingestion; will resolve to `/api/events/ingest`
endpoint = "/events/ingest"
# API key to authenticate incoming requests
# The service will hash this automatically on startup
# Use header: x-api-key
api-key = "some-value"
