[server]
host = "0.0.0.0"
port = 8000
production = true
cors-url = ["http://localhost:3000"]

[server.security]
jwt-secret = "testing1234555"

[app]
auth-required = false
event-logging = true
event-log-file = "events.log"
event-log-rotation = "8h"
event-segment-size = 1000
event-max-segments = 10

[app.events.http]
# Endpoint for HTTP events ingestion; will resolve to /api/events/ingest
endpoint = "/events/ingest"
# API key to authenticate incoming requests
# The service will hash this automatically on startup
# Use header: x-api-key
api-key = "some-value-of-size-16-characters"
